data:
  type: image
  train_dir: /hpchome/carin/mz149/data/102flowers/
  test_dir: /hpchome/carin/mz149/data/102flowers/
  img_size: 256
  nlabels: 1
generator:
  name: resnet4_AdaFM_bias
  layers: -4
  kwargs:
    nfilter: 64
    embed_size: 1
discriminator:
  name: resnet4_AdaFM_bias
  layers: 2
  kwargs:
    nfilter: 64
    embed_size: 1
encoder:
  name: resnet4_AdaFM_bias
  layers: 2
  kwargs:
    nfilter: 64
    embed_size: 1
z_dist:
  type: gauss
  dim: 256
training:
  out_dir: F:/RUN_CODE_OUT/GAN_stability/noPreInitial/celebA_fix_ImageNet
  gan_type: standard
  reg_type: real
  reg_param: 10.
  batch_size: 6
  nworkers: 0
  take_model_average: true
  model_average_beta: 0.999
  model_average_reinit: false
  monitoring: none
  sample_every: 1000
  sample_nlabels: 10
  inception_every: 5000
  backup_every: 5000
  restart_every: -1
  optimizer: adam
  lr_g: 0.0001
  lr_d: 0.0001
  lr_anneal: 1.
  lr_anneal_every: 150000
  d_steps: 1
  equalize_lr: false
test:
  model_file: F:/RUN_CODE_OUT/GAN_stability/pretrained/models/celeba-ab478c9d.pt
  batch_size: 16
  sample_size: 16
  sample_nrow: 4
  conditional_samples: 1
interpolations:
  nzs: 10
  nsubsteps: 75


##model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/gan_stability/models/celeba-ab478c9d.pt
